Enhance useStream with default value
ardoq/rxbeach pull request #324
Opened 2021-06-24 10:21 UTC by michaltaberski

2021-06-24 11:46 UTC, tlaundal requested changes
Nice idea, could you give a use case example? I'm a bit curious as to how the call site would look with and without this.

Requesting changes because the docstring must be updated and we should add a small test for this.

2021-07-01 08:05 UTC, tlaundal approved these changes
Vacation review on mobile, but LGTM!

2021-07-01 08:14 UTC, michaltaberski commented
It's not critical PR, so it can wait for a proper review once you are back. Enjoy!

2021-08-02 08:43 UTC, tlaundal approved these changes
:100:

2021-08-02 08:43 UTC, tlaundal commented on src/react/connect.ts
>   * has no guarantee for when the first emit will happen.
```suggestion
 * has no guarantee for when the first emit will happen. This initial
 * value may be overridden with the `defaultValue` argument.
```

2021-08-02 08:43 UTC, tlaundal commented on src/react/connect.ts
> +  defaultState?: T
```suggestion
  defaultValue?: T
```
Keep in line with the `@param` above.

2022-02-22 12:44 UTC, merged